jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_USER}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  credentials:
    system:
      domainCredentials:
        - credentials:
            - string:
                scope: GLOBAL
                id: "docker-registry-credentials"
                secret: ${DOCKER_REGISTRY_TOKEN}
                description: "Docker Registry Token"
            - usernamePassword:
                scope: GLOBAL
                id: "github-credentials"
                username: ${GITHUB_USER}
                password: ${GITHUB_TOKEN}
                description: "GitHub Credentials"

jobs:
  - script: >
      pipelineJob('kf-monolith-clients-bank') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/your-username/kf-monolith-clients-bank.git')
                  credentials('github-credentials')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          githubPush()
        }
      }
